name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler: '4.0.11'
          bundler-cache: true

      - name: Build site
        env:
          JEKYLL_ENV: production
        run: bundle exec jekyll build --config _config.yml